# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 16:18
from __future__ import unicode_literals

from django.db import migrations
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=pgcrypto.fields.EncryptedCharField(blank=True, charset=b'utf-8', check_armor=True, cipher=b'AES', verbose_name='Name of User', versioned=False),
        ),
    ]
