# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180327_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name=b'name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of User'),
        ),
    ]
