# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 18:09
from __future__ import unicode_literals

from django.db import migrations
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180328_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
