# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 15:49
from __future__ import unicode_literals

from django.db import migrations
import pgcrypto_expressions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=pgcrypto_expressions.fields.EncryptedTextField(blank=True, max_length=255, verbose_name='Name of User'),
        ),
    ]
