# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 16:06
from __future__ import unicode_literals

from django.db import migrations
import pgcrypto_expressions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180327_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=pgcrypto_expressions.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Name of User'),
        ),
    ]
